<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * English language strings for local_ai_coursecreator.
 *
 * @package   local_ai_coursecreator
 * @copyright 2026 Highskills and more <info@highskills.co.il>
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

// Plugin name.
$string['pluginname'] = 'AI Course Creator';

// Capability.
$string['ai_coursecreator:generate'] = 'Generate courses with AI';

// Role.
$string['rolename']        = 'AI Course creator';
$string['roledescription'] = 'Users in this role can generate AI-assisted courses. Based on the manager archetype. Can be assigned at system or category level by site administrators only.';

// Admin settings.
$string['settings_stream_url']          = 'Stream endpoint URL';
$string['settings_stream_url_desc']     = 'Full URL of the AI pipeline streaming endpoint, including the tenant path (e.g. https://api.example.com/api/v1/process-stream/your-tenant-id).';
$string['settings_api_key']             = 'API Key';
$string['settings_api_key_desc']        = '64-character hex key shown in the admin UI after creating or regenerating the tenant.';
$string['settings_stream_timeout']         = 'Stream timeout (seconds)';
$string['settings_stream_timeout_desc']    = 'Maximum seconds to wait for the AI pipeline to complete. Increase for large documents (PDFs, long texts). Minimum 30. Default 600 (10 minutes).';
$string['settings_system_prompt']          = 'System prompt';
$string['settings_system_prompt_desc']     = 'Optional text prepended to every course source submission. Use this to give the AI standing instructions (e.g. language, tone, curriculum standards). Leave blank to send only the teacher\'s text.';
$string['settings_diagnostics_heading']    = 'Diagnostics';

// Index page.
$string['page_title']         = 'Generate Course with AI';
$string['source_text_label']  = 'Course source text';
$string['source_text_help']   = 'Paste lecture notes, a syllabus, or any document you want to convert into a Moodle course.';
$string['generate_btn']          = 'Generate Course';
$string['include_images_label']  = 'Include image generation';
$string['progress_heading']   = 'Generation progress';

// Progress row labels.
$string['agent_analyst']      = 'Agent 1: Analyst';
$string['agent_architect']    = 'Agent 2: Architect';
$string['agent_writer']       = 'Agent 3: Writer';
$string['image_generator']    = 'Image Generator';
$string['mbz_builder']        = 'MBZ Builder';

// Status labels.
$string['status_waiting']     = 'Waiting…';
$string['status_running']     = 'Running…';
$string['status_done']        = 'Done';

// Result area.
$string['result_heading']     = 'Course ready';
$string['result_title_label'] = 'Course title:';
$string['result_size_label']  = 'File size:';
$string['restore_btn']        = 'Restore as new course';
$string['backup_area_link']   = 'View in backup area';

// File upload.
$string['upload_label']       = 'Upload source files (optional)';
$string['upload_help']        = 'Accepted: .txt, .csv, .html, .docx, .pdf. Content is extracted and combined with any text entered above.';
$string['upload_no_input']    = 'Please enter source text or upload at least one file.';
$string['input_too_large']    = 'The source content exceeds the 512 KB plain-text limit. Please reduce the amount of text or split it across multiple generations.';

// Error.
$string['error_heading']      = 'Generation failed';
$string['error_unknown']      = 'An unknown error occurred. Please try again.';

// Restore.
$string['restore_success']    = 'Course restored successfully.';
$string['restore_failed']     = 'Restore failed: {$a}';
$string['no_mbz_in_session']  = 'No generated course found in your session. Please generate a course first.';

// Security / config errors.
$string['api_not_configured'] = 'The AI Course Creator service is not fully configured. Please ask your administrator to set the stream endpoint URL and API key.';
$string['ssl_warning']        = 'Warning: SSL certificate verification is disabled because the API URL uses HTTP. Configure HTTPS in production.';
$string['curlerror']          = 'Could not reach the AI service: {$a}';
$string['apierror']           = 'The AI service returned an error: {$a}';
$string['ai_disclaimer']      = '⚠️ Course content is generated by AI and may contain inaccuracies, outdated information, or errors. Always review and validate before publishing to students.';
